<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Approximately' => 'Circa',
    'Comment' => '',
    'ID' => '',
    'Link To Photo' => '',
    'Problem ID' => '',
    'Room ID' => '',
    'Server Path' => '',
    'Buthtub/Two Room' => 'Con vasca/Doppia',
    'Doors/Windows' => 'Porte/finestre',
    'Floor/Walls/Roof' => 'Pavimento/Parete/Soffitto',
    'Furniture' => 'Mobili',
    'In progress' => 'In corso',
    'New Problem' => 'Nuovo problema',
    'Normal' => 'Normale',
    'Sanitary' => 'Idraulico',
    'Solved' => 'Risolto',
    'Terrace' => 'Terrazza',
    'Terrace/Buthtub' => 'Terazza/Con vasca',
    'Toilet' => 'Toilette',
    'Are you sure you want to delete this item?' => 'Sei sicuro di voler eliminare questo elemento?',
    'Category' => 'Categoria',
    'Create problem' => 'Creare problema',
    'Create room' => 'Creare camera',
    'Delete' => 'Elimina',
    'Number' => 'Numero',
    'Number of problems' => 'Numero di problemi',
    'Place' => 'Località',
    'Problem' => 'Problema',
    'Problems' => 'Problemi',
    'Room' => 'Camera',
    'Room number' => 'Numero di camera',
    'Rooms' => 'Camere',
    'Status' => 'Stato',
    'Type' => 'Tipo',
    'Update' => 'Aggiorna',
    'Update Problem: ' => 'Aggiorna il problema: ',
    'For pay' => 'Pagherai',
    'Price' => 'Prezzo',
    'The company that issued your card may charge you a fee on transactions abroad.' => 'La società che ha emesso la tua carta potrebbe addebitarti una tassa sulle transazioni estere.',
    'The total price shown is the amount that you pay at the structure' => 'Il prezzo totale indicato è l\'importo che pagherai',
];
